version: "3.9"

services:
  pgdatabase:
    image: postgres:11
    container_name: pgdatabase
    restart: unles-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      